name: Mix plugin

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libc6:i386 libstdc++6:i386

      - name: download AMX Mod X Compiler (1.10)
        run: |
          wget https://www.amxmodx.org/amxxdrop/1.10/amxmodx-1.10.0-git5479-base-linux.tar.gz
          tar -xzf amxmodx-1.10.0-git5479-base-linux.tar.gz

          mkdir -p tools/amxx
          cp -r addons/amxmodx/scripting/* tools/amxx/

          chmod +x tools/amxx/amxxpc
          chmod +x tools/amxx/*.so

      - name: inspect compiler
        run: |
          ls -lah tools/amxx
          file tools/amxx/amxxpc
          find tools/amxx -maxdepth 1 -type f -name "*.so" -print

      - name: compile (.sma -> .amxx)
        run: |
          chmod +x tools/amxx/* 2>/dev/null || true
          make compile

      - name: inspect compiled plugin
        run: |
          ls -lah build/
          file build/mix.amxx
          xxd -l 32 build/mix.amxx

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          name: "latest build"
          tag_name: "latest"
          prerelease: true
          files: build/mix.amxx
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
